export const ID_VERIFY_REQUEST = 'ID_VERIFY_REQUEST'
export const ID_VERIFY_SUCCESS = 'ID_VERIFY_SUCCESS'
export const ID_VERIFY_FAIL = 'ID_VERIFY_FAIL'

export const IMAGE_VERIFY_REQUEST = 'IMAGE_VERIFY_REQUEST'
export const IMAGE_VERIFY_SUCCESS = 'IMAGE_VERIFY_SUCCESS'
export const IMAGE_VERIFY_FAIL = 'IMAGE_VERIFY_FAIL'
